name: deploy to oss

on:
  push:
    branches:
      - main-oss

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # load repo to /github/workspace
      - uses: actions/checkout@v2
        with:
          repository: maqi1520/mdx-editor
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      # 打包文档命令
      - run: npm run build
      - name: upload files to OSS
        uses: go-choppy/ossutil-github-action@master
          with:
            ossArgs: 'cp -r -u .next/static oss://.next/static'
            endpoint: "oss-cn-hangzhou.aliyuncs.com"
            accessKey: ${{ secrets.ACCESS_KEY_ID }}
            accessSecret: ${{ secrets.ACCESS_KEY_SECRET }}
